### ISSUE TITLE
import command fails when filename contains '-' 

### ISSUE THREAD

**Issue by dhrp** [corneliusweig/konfig#7]
STR:

`kubectl konfig import ingress-test-config.yaml `
> `error: unrecognized flag "ingress-cluster.yaml"`

It probably has something to do with how you get input flags.

-- Very happy that I found this tool! Thanks for creating it!

Actually...
`kubectl konfig import -s ingresscluster.yaml`
or `kubectl konfig import --save ingresscluster.yaml`

also fails with:
`error: unrecognized flag "-s ingresscluster.yaml"`

**Comment by corneliusweig** [comment]
Hey @dhrp, thanks for reporting this! I fixed the bug with the hyphens in filenames, but I cannot reproduce your second issue (the one you added lateron). Can you please run as
```
DEBUG=yes kubectl konfig ...
```
This will show what commands are actually run and may give a clue as to what is going on.

Glad you like the tool :)

---

PS: you can hot-patch your installation with
```
sed -i '89celif [[ "${1}" =~ ^-(.*) ]]; then' `which kubectl-konfig`
```
I would like to resolve your issue completely before publishing a new release.

**Comment by dhrp** [comment]
HI @corneliusweig 

Thanks for the quick response.. 

Unfortunately, it seems this does not resolve the issue, and I've now actually spend more time than I would have thought to have needed digging into the situation. Turns out that I have bash 3.2, which is the default on Mac OS (still). 

And it doesn't play nice with passing arrays as arguments to functions. More specifically, because you set the IFS to not contain space, the arrays will be passed as a single word, not an array. Notice the quotes around `error: unrecognized flag "-s ingresscluster.yaml"`

Now, I thought I could send you a patch or PR, but I don't quite understand why you change the IFS in the first place, though removing it does make the tests fail.

```
Oatcake:.kube thatcher$ DEBUG=yes kubectl konfig import -s ingresscluster 
+ set -eou pipefail
+ IFS=':
	'
+ TMPFILES=()
+ declare -a TMPFILES
+ trap cleanup EXIT
+ main import -s ingresscluster
+ hash kubectl
+ KUBECTL=kubectl
+ [[ 3 -eq 0 ]]
+ case "$1" in
+ import_ctx '-s ingresscluster'
+ local tmpcfg
+ local out=
+ [[ -s ingresscluster = \-\-\s\a\v\e ]]
+ [[ -s ingresscluster = \-\s ]]
+ [[ -s ingresscluster =~ -(.*) ]]
+ error 'unrecognized flag "-s ingresscluster"'
+ echo 'error: unrecognized flag "-s ingresscluster"'
error: unrecognized flag "-s ingresscluster"
+ exit 1
+ cleanup
+ [[ 0 -gt 0 ]]
```

**Comment by corneliusweig** [comment]
Hey @dhrp, thanks for investing so much into the analysis here! I use `IFS` to expand the list of kubeconfigs to `konfig1:konfig2:konfig3` such that I can set the env var `KUBECONFIG=konfig1:konfig2:...`.
I'll have to see if I can find another way to achieve the same goal.

I'm so sorry that this has cost you more time than it will probably save you :( But I'm extremely grateful that you have reported this and helped in finding a solution.

PS: After you applied the hot-patch you will probably have problems with `krew`. When you are done with debugging `konfig` and want to continue using `krew`, please do `rm -i $(which kubectl-konfig)` and at your convenience you can re-install `konfig` via `krew`. I only found out about this glitch after I left the previous comment.

**Comment by corneliusweig** [comment]
@dhrp Thanks to your help I could reproduce the issue and found a fix (https://github.com/corneliusweig/konfig/pull/9). I'll publish the fixed version asap, so that it will be available in `krew`.
